### ISSUE TITLE
Lint to find duplicate indexes

### ISSUE THREAD

**Issue by ivasilov** [supabase/splinter#20]
We can find the same indexes which only differ by index name by using 
```
SELECT array_agg(indexname) AS indexes, replace(indexdef, indexname, '') AS defn
    FROM pg_indexes
GROUP BY defn
  HAVING count(*) > 1;
```

**Comment by olirice** [comment]
thats a nice solution for detecting them easily

**Comment by ivasilov** [comment]
This rule is misreporting on tables which have two unrelated indexes to each other. I'm using the Slack clone template to test.
![Screenshot 2024-04-09 at 12 22 15](https://github.com/supabase/splinter/assets/568291/2f9796a0-0f86-4cbd-a3ae-f8a14c5139de)
