### ISSUE TITLE
Suggestion: add a 'docs link' in response / or use markdown for links in details

### ISSUE THREAD

**Issue by MildTomato** [supabase/splinter#33]
# Chore

## Describe the chore

An example of a URL for a docs link can be seen [here](https://github.com/supabase/splinter/blob/264ee0a080e7664571254d45a59e9b92f1efe2c4/lints/0003_auth_rls_initplan.sql#L63-L67)

Might be more useful for formatting responses if this was in markdown, or perhaps maybe we add another column in view for a docs link. Make it easier to build a user interface around linting responses.

## Additional context

Add any other context or screenshots that help clarify the task.

**Comment by olirice** [comment]
We have the `remediation` column that contains a reference to the docs here
https://github.com/supabase/splinter/blob/264ee0a080e7664571254d45a59e9b92f1efe2c4/lints/0003_auth_rls_initplan.sql#L68

is that what you're looking for, or did I misunderstand?

**Comment by olirice** [comment]
remediation now points to the [official supabase docs](https://supabase.com/docs/guides/database/database-linter), which mirrors `docs/` 

we also use markdown for text blocks

pls re-open if I misunderstood the issue
