### ISSUE TITLE
Lint for `reg<whatever>` types outside of `pg_catalog`

### ISSUE THREAD

**Issue by olirice** [supabase/splinter#55]
pg_upgrade does not support upgrading of databases containing table columns using these reg* OID-referencing system data types:
- regcollation
- regconfig
- regdictionary
- regnamespace
- regoper
- regoperator
- regproc
- regprocedure

(regclass, regrole, and regtype can be upgraded.)

This task is to add a `WARN` lint to notify users they will not be able to upgrade their database without first removing references to those types

**Comment by bymayanksingh** [comment]
Hi @olirice,

I'm interested in working on this issue as my first contribution to Supabase. I'm new to the project, so far I've been referring the files in the repo itself & trying to understand the project, additionally I am reading https://supabase.github.io/splinter/ docs.

Can you assign this to me?

**Comment by olirice** [comment]
sounds great, I assigned it to you
looking forward to reviewing!

let me know if you get stuck on anything

**Comment by bymayanksingh** [comment]
@olirice I raised a WIP PR for this, can you tell me what will be the most suitable category to used while writing the lint for the above?

`ARRAY['CATEGORY'] AS categories`

Current Categories.
- PERFORMANCE
- SECURITY
- etc.

**Comment by olirice** [comment]
resolved by #92 

thanks again, this may take 1-3 days to show up in Supabase Studio on production

**Comment by bymayanksingh** [comment]
Sure thanks @olirice 
Should we close this issue?
