### ISSUE TITLE
Performance Advisor showing warning for Auth RLS Initialization Plan after policy has been fixed

### ISSUE THREAD

**Issue by Crypto69** [supabase/splinter#63]
I'm using hosted supabase. After watching the excellent video [8 things you should NEVER do in a Database](https://youtu.be/NZEbVe47DfA?si=owNjgDSOQhKDjdjT)
I decided to check my project.

I had multiple Auth RLS Initialization Plan warnings because my policies we're all written as `using ( auth.uid() = user_id );` instead of` using ( (select auth.uid()) = user_id );`

I changed my policy as suggested (and yes I did save the changes).

But the warnings have not gone away. Attached screenshots show the policy and the warning

![Screenshot 2024-04-22 at 5 34 14 pm](https://github.com/supabase/splinter/assets/50306702/01ab3ad2-5556-4f0c-b1ab-173499cfe35b)

![Screenshot 2024-04-22 at 5 34 27 pm](https://github.com/supabase/splinter/assets/50306702/9c5cffc9-508a-4d2e-b463-836e20507312)

![Screenshot 2024-04-22 at 5 34 58 pm](https://github.com/supabase/splinter/assets/50306702/6a9bf2ef-b16d-4b20-a98d-b8f753a1d27c)

I tried doing the same for all my warnings but none of them go away.
I also tried pressing rerun linter multiple times

I followed the documentation [here](https://supabase.com/docs/guides/database/postgres/row-level-security#call-functions-with-select) and even tried creating a new table but had the same result. I'm not sure if I'm doing something wrong or this is a bug?

**Comment by LukeHosk** [comment]
Ran across the same issue myself, and have just created a minimal reproduction repo and confirmed that the linter flags this there too.

https://github.com/LukeHosk/splinter-rls-initialization-plan-repro

---

<img width="1000" alt="Screenshot 2024-04-22 at 15 22 50" src="https://github.com/supabase/splinter/assets/74842299/e6e9786a-22a5-4ee0-ab7f-c4f18a40742d">


<img width="1000" alt="Screenshot 2024-04-22 at 15 21 11" src="https://github.com/supabase/splinter/assets/74842299/8bd10286-5ee9-463a-92c7-0ecc01575bab">

**Comment by PfernFSU** [comment]
This same thing is happening to me and I also came here to report it.
Bad RLS query that was flagged:
```  
( SELECT (EXISTS ( SELECT 1
           FROM admin_users a
          WHERE (auth.uid() = a.id))) AS "exists")
```

I updated it to the following, saved it, and re-ran the linter and it still fails:
```
  (EXISTS ( SELECT 1
   FROM admin_users admin
  WHERE (( SELECT auth.uid() AS uid) = admin.id)))
```

**Comment by juskuc** [comment]
Running into the same issue that the guys above have mentioned. Were there any recent changes to the code that could have broken it again?

**Comment by olirice** [comment]
no changes @juskuc. could you please provide a project ref? I'll check the logs
