### ISSUE TITLE
Space at end of column name.

### ISSUE THREAD

**Issue by GaryAustin1** [supabase/splinter#76]
It is still a common occurrence users get a space at the end of a column name.  This is extremely hard to spot in the UI and in the table definition it generates as there are not "" around the names.
Example:
https://github.com/orgs/supabase/discussions/26023

Might be good to flag column names with a space at the end as I cannot think of a good use case for that.

**Comment by olirice** [comment]
thanks

I've added some metadata collection to the data eng pipeline to check how many instance of these exist. If its a common problem (more than 100 unique projects) we'll add it

I'll follow up nlt Wednesday once that data has been collected

**Comment by GaryAustin1** [comment]
Turns out the latest OP was running an older version of the CLI that did not have the trimming in it.

**Comment by olirice** [comment]
in that case, should we close this? or is it still worth scanning to see if anyone else is impacted?

**Comment by olirice** [comment]
We currently have 0 impacted projects in the hosted environment so I'm going to close this for now.
lmk if you see another one come by
