### ISSUE TITLE
Make the repo easier to find

### ISSUE THREAD

**Issue by tvogel** [supabase/splinter#91]
# Make the repo easier to find

## Link 

https://github.com/supabase/splinter

## Describe the problem

In the supabase documentation, the `splinter` is referred to as "Performance and Security Advisors" and it would be good to include that in the name of the repository, so it is easier to find when searching for "security advisor" in the `supabase` github org.

## Describe the improvement

Change the repository description to "Supabase Postgres Linter: Performance and Security Advisors".

**Comment by olirice** [comment]
good idea, thanks
done
