### ISSUE TITLE
Update advice for Auth RLS Initialization Plan

### ISSUE THREAD

**Issue by cyluss** [supabase/splinter#97]
# Improve documentation

## Link 

[0003 auth rls initplan](https://supabase.com/docs/guides/database/database-advisors?queryGroups=lint&lint=0003_auth_rls_initplan)

## Describe the problem

1. The document suggests 'Call functions with select' from [RLS performance recommendation guide](https://supabase.com/docs/guides/database/postgres/row-level-security#rls-performance-recommendations) but the recommendation does not resolve lint error.
2. Readers might not know if RLS performance recommndation exists, since readers are navigated from Supabase Studio in the performance advisor.

## Describe the improvement

1. Suggest 'Use security definer functions' instead.
2. Add Reference section and link to RLS performance recommedation.

## Additional context

supabase/supabase#23185

**Comment by olirice** [comment]
> The document suggests 'Call functions with select' from [RLS performance recommendation guide](https://supabase.com/docs/guides/database/postgres/row-level-security#rls-performance-recommendations) but the recommendation does not resolve lint error.

could you please provide a reproducible example for me to test with?

> Suggest 'Use security definer functions' instead.

I don't understand this recommendation. There are no functions involved with table access or RLS. Could you please expand on that?

**Comment by cyluss** [comment]
Sorry for the confusion, this issue is invalid and related issue (supabase/supabase#23185) is not reproducible and closed
